[package]
name = "can"
version = "0.1.0"
edition = "2021"

[features]
default = ["bxcan"]

[dependencies]
bxcan = { version = "0.7.0", optional = true }
embedded-hal = "0.2.7"
futures = "0.3.28"
nb = "1.1.0"
