[package]
name = "async-hal"
version = "0.1.0-alpha.1"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "Async hardware abstraction layer for embedded devices"

[features]
mock = []
default = ["bxcan", "mock"]

[dependencies]
bxcan = { version = "0.7.0", optional = true }
embedded-hal = "0.2.7"
futures = { version = "0.3.28", default-features = false }
nb = "1.1.0"

[dev-dependencies]
tokio = { version = "1.28.1", features = ["full"] }
